//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entegre_otomasyonu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Drawing;
    using System.IO;

    public partial class kategori
    {
        public int k_id { get; set; }
        public string k_ürünadı { get; set; }
        public string k_marka { get; set; }
        public string k_ürünkategorisi { get; set; }
        public string k_montajtipi { get; set; }
        public string k_kılıf { get; set; }
        public string k_regülatörtipi { get; set; }
        public string k_çıkışakımı { get; set; }
        public string k_girişgerilimi { get; set; }
        public string k_çıkışgerilimi { get; set; }
        public string k_çalışmasıcaklığı { get; set; }
        public string k_rohs { get; set; }
        public string k_fiyat { get; set; }
        public string k_imagefile { get; set; }
        [NotMapped]
        public Image Resim
        {
            get {
                if (!string.IsNullOrEmpty(k_imagefile)) {
                    if (File.Exists(k_imagefile))
                        return Image.FromFile(k_imagefile);
                }
                return null;
            }
        }
    }
}
